name = "backend"
compatibility_date = "2024-07-13"


[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMmYxMzI5MGMtZTgxOC00NDhkLTljMTAtYjJlOWU2MTgzMDA0IiwidGVuYW50X2lkIjoiMDFkYTE0ZmUxYmZiM2IwMDY2MWIyYTc3YWQwODhhOWJiMzQzZTBkODFlZTExNDI3YzIwMGIyNGUwY2JjNjFjYiIsImludGVybmFsX3NlY3JldCI6IjE0Y2U2NTc3LTBlMDItNDFkOC1hN2E2LTMyM2ZmODFjNmJiMSJ9.HOBAJoEFFOmpZjDOFQRPQ_CawRWZ7EBO4pIQBqn41zg"

JWT_SECRET="verysecretkey"
# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"
